name: another context
on:
  workflow_run:
    workflows: [test, asdfasdf]
    types: [completed]
    branches: [main]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: go
        run: echo "works"
