name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{steps.released_version.outputs.version}}
    steps:
      - uses: rymndhng/release-on-push-action@master
        id: released_version
        with:
          bump_version_scheme: patch
  update:
    name: update go pkg with new release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: setup go server
        uses: actions/setup-go@v1
        with:
          go-version: "1.19"
      - name: update go pkg with new release
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: "on"
          VERSION: ${{needs.test.outputs.released_version}}
        run: |
          go mod init pipeline
          go get github.com/gritzkoo/golang-health-checker-lw@v${VERSION}
