name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.ola.output.version}}
    steps:
      - name: testing
        id: ola
        run: echo "version=1.0.1" >> $GITHUB_OUTPUT
  update:
    name: update go pkg with new release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: setup go server
        uses: actions/setup-go@v1
        with:
          go-version: "1.19"
      - name: update go pkg with new release
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: "on"
          VERSION: ${{needs.test.outputs.version}}
        run: |
          echo "version: ${VERSION} outputs: ${{needs.test.outputs.version}}"
          go mod init pipeline
          go get github.com/gritzkoo/golang-health-checker-lw@v${VERSION}
